server:
  port: 8761

spring:
  application:
    name: discovery-server
  security:
    user:
      name: ${EUREKA_USER:eureka}
      password: ${EUREKA_PASSWORD:eureka_pass}

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
